/** Offline browser UAT: real HTTP business routes; explicitly mocked LLM/OCR. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {spawn}=require('child_process'),fs=require('fs'),path=require('path'),os=require('os');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'docs/business-v3/evidence');fs.mkdirSync(out,{recursive:true});
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'resultscope-uat-'));const port=8098,base='http://127.0.0.1:'+port;
const py=process.env.TEST_PYTHON||path.join(root,'.venv',process.platform==='win32'?'Scripts/python.exe':'bin/python');
const server=spawn(py,['tests/browser/fixture_server.py'],{cwd:root,env:{...process.env,PROVIDER_NETWORK_ENABLED:'false',BUSINESS_DB_PATH:path.join(tmp,'db.sqlite'),BUSINESS_KEY_PATH:path.join(tmp,'key'),DATABASE_URL:'',VERCEL:'',RENDER:'',APP_ENV:'test'},stdio:['ignore','ignore','pipe']});let log='';server.on('error',e=>{log+='Fixture process failed: '+e.message;});server.stderr.on('data',x=>log+=x);
let browser;let records=[],errors=[];const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function check(name,fn){const start=Date.now();try{await fn();records.push({name,status:'PASS',ms:Date.now()-start});}catch(e){records.push({name,status:'FAIL',ms:Date.now()-start,error:e.message});throw e;}}
const assert=(cond,msg)=>{if(!cond)throw Error(msg)};
(async()=>{try{
 for(let i=0;i<60;i++){try{if((await fetch(base+'/health')).ok)break;}catch{}await wait(250);if(i===59)throw Error('Fixture server unavailable: '+log.slice(-1500));}
 browser=await chromium.launch({headless:true,args:['--no-sandbox']});const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));
 await check('Homepage: six supplied images and English navigation',async()=>{await p.goto(base,{waitUntil:'networkidle'});assert(await p.locator('img').count()===6,'Six photos missing');assert(await p.locator('.package-card').count()===3,'Packages missing');await p.screenshot({path:path.join(out,'homepage-desktop.png'),fullPage:true});});
 await check('Workspace: free-text first and account creation',async()=>{await p.goto(base+'/app',{waitUntil:'networkidle'});await p.locator('#message').waitFor();await p.locator('#account-open').click();await p.getByLabel('Email address').fill('customer@example.invalid');await p.getByLabel('Password',{exact:true}).fill('ui-test-only-password');await p.getByRole('button',{name:'Create account',exact:true}).click();await p.locator('#modal').waitFor({state:'hidden'});assert((await p.locator('#account-label').innerText()).includes('customer@'),'Account missing');});
 await check('Chat proposal does not book until confirmation',async()=>{await p.locator('#message').fill('UI_TEST_BOOK');await p.getByRole('button',{name:'Send message',exact:true}).click();await p.getByRole('button',{name:'Confirm booking',exact:true}).waitFor();const w=await ctx.request.get(base+'/api/business/workspace');assert((await w.json()).bookings.length===0,'Premature booking');await p.screenshot({path:path.join(out,'chat-preview.png')});});
 await check('Confirm creates exactly one appointment with canonical price',async()=>{await p.getByRole('button',{name:'Confirm booking',exact:true}).click();await p.locator('[data-view=bookings]').click();await p.getByText('Payment: pending',{exact:true}).waitFor();assert((await p.locator('#content').innerText()).includes('1,690'),'Incorrect price');await p.screenshot({path:path.join(out,'appointment.png')});});
 await check('Payment at center stays pending',async()=>{await p.getByRole('button',{name:'Pay at center',exact:true}).click();await p.getByText('Payment: pending',{exact:true}).waitFor();});
 await check('Upload opens source image and editable unconfirmed fields (OCR double)',async()=>{await p.locator('[data-view=reports]').click();await p.locator('#report-file').setInputFiles(path.join(root,'examples/thai_lab_reference_v3/png/04_B_Glucose_Urine.png'));await p.getByRole('heading',{name:'Review report fields',exact:true}).waitFor();await p.locator('.report-preview').evaluate(img=>img.decode());assert(await p.locator('.report-preview').evaluate(img=>img.naturalWidth>0),'Source image missing');await p.getByLabel('value for row 1',{exact:true}).fill('101');await p.screenshot({path:path.join(out,'report-review.png')});});
 await check('Explicit field confirmation and selected context',async()=>{await p.locator('#modal input[type=checkbox]').check();await p.getByRole('button',{name:'Confirm and use report',exact:true}).click();await p.locator('#modal').waitFor({state:'hidden'});await p.locator('#context-report').filter({hasText:'Selected:'}).waitFor();});
 await check('Archive and saved report survive reload',async()=>{await p.locator('#new-chat').click();await p.reload({waitUntil:'networkidle'});await p.locator('[data-view=history]').click();await p.getByRole('button',{name:'Read conversation',exact:true}).waitFor();await p.locator('[data-view=reports]').click();await p.getByRole('button',{name:'Review fields',exact:true}).waitFor();});
 await check('Staff handoff consent queues the conversation',async()=>{await p.locator('#staff-request').click();await p.getByLabel('How can our team help?').fill('UI UAT organization assistance');await p.getByRole('button',{name:'Send staff request',exact:true}).click();await p.locator('#modal').waitFor({state:'hidden'});});
 const staffCtx=await browser.newContext({viewport:{width:1440,height:1000}}),s=await staffCtx.newPage();s.on('pageerror',e=>errors.push(e.message));
 await check('Staff signs in and takes over a case',async()=>{await s.goto(base+'/staff',{waitUntil:'networkidle'});await s.locator('#account-open').click();await s.getByLabel('Email address').fill('staff@example.invalid');await s.getByLabel('Password',{exact:true}).fill('ui-test-only-password');await s.locator('#modal').getByRole('button',{name:'Sign in',exact:true}).click();await s.locator('#modal').waitFor({state:'hidden'});await s.getByRole('button',{name:/UI UAT organization assistance/}).click();await Promise.all([s.waitForResponse(r=>r.url().endsWith('/state')&&r.request().method()==='POST'),s.getByRole('button',{name:'Take over',exact:true}).click()]);await s.getByText('Case: staff',{exact:true}).waitFor();});
 await check('Live website staff reply reaches customer',async()=>{await s.getByLabel('Staff reply').fill('A staff member is reviewing your organization request.');const [response]=await Promise.all([s.waitForResponse(r=>r.url().includes('/tickets/')&&r.url().endsWith('/messages')&&r.request().method()==='POST'),s.getByRole('button',{name:'Send reply',exact:true}).click()]);assert(response.ok(),'Staff reply failed: '+await response.text());await p.bringToFront();await p.locator('[data-view=chat]').click();await p.getByText('A staff member is reviewing your organization request.',{exact:true}).waitFor({timeout:12000});await s.screenshot({path:path.join(out,'staff-inbox.png')});});
 await check('Manager operations and catalog are available',async()=>{await s.getByRole('button',{name:'Bookings, catalog and delivery status',exact:true}).click();await s.getByRole('heading',{name:'Catalog management',exact:true}).waitFor();assert(await s.getByRole('button',{name:'Save package',exact:true}).count()===18,'Catalog incomplete');await s.locator('#modal-close').click();});
 await check('Desktop keyboard focus visible and no overflow',async()=>{await p.keyboard.press('Tab');assert(await p.evaluate(()=>!!document.activeElement),'No focus');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow');});
 const mobile=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));
 await check('390px fresh-load mobile navigation and reduced motion',async()=>{await mp.goto(base+'/app',{waitUntil:'networkidle'});await wait(300);assert(await mp.locator('#sidebar').evaluate(e=>e.inert),'Drawer should be inert');console.log('MOBILE',await mp.locator('#send,#chat-view,.workspace-body,.conversation-column,.composer-area,.context-panel').evaluateAll(es=>es.map(e=>({name:e.className,w:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right,display:getComputedStyle(e).display}))));assert(await mp.locator('#send').evaluate(e=>e.getBoundingClientRect().right<=innerWidth),'Send button clipped');await mp.screenshot({path:path.join(out,'workspace-mobile.png')});await mp.locator('#menu-toggle').click();await mp.locator('[data-view=packages]').click();await mp.locator('.package-card').nth(17).waitFor();assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow');});
 await check('Mobile photographic home has no horizontal overflow',async()=>{await mp.goto(base,{waitUntil:'networkidle'});assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Home overflow');await mp.screenshot({path:path.join(out,'homepage-mobile.png'),fullPage:true});});
 await check('No browser JavaScript errors',async()=>assert(!errors.length,JSON.stringify(errors)));
 }catch(e){console.error(e.message);process.exitCode=1;}finally{
 fs.writeFileSync(path.join(out,'browser-uat.json'),JSON.stringify({date:new Date().toISOString(),mode:'OFFLINE — real UI/API/storage; LLM and OCR test doubles; not clinical/model validation',records,errors},null,2));console.log(JSON.stringify(records));if(browser)await browser.close();server.kill();}
})();
