'use strict';
const $=id=>document.getElementById(id);
const orgLabel=s=>s==='Siriraj Hospital'?'ศิริราช':s==='Srinagarind Hospital, KKU'?'ศรีนครินทร์ มข.':s;
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function range(r){if(r.lower===null)return (r.upper_inclusive?'≤ ':'< ')+r.upper+' '+r.unit;if(r.upper===null)return (r.lower_inclusive?'≥ ':'> ')+r.lower+' '+r.unit;return r.lower+' – '+r.upper+' '+r.unit;}
function context(r){return [r.sex==='male'?'ชาย':r.sex==='female'?'หญิง':'ไม่ได้แบ่งตามเพศในรายการนี้',r.age_text?'อายุ: '+r.age_text:'ต้นฉบับไม่ได้ระบุช่วงอายุในแถวนี้'].join(' · ');}
function sourceLink(text,url){const a=el('a',text);const u=new URL(url,window.location.origin);if(u.protocol!=='https:'&&u.origin!==window.location.origin)throw new Error('invalid source URL');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';return a;}
function record(r){const a=el('article',undefined,'record'),top=el('div',undefined,'record-title');top.append(el('h3',r.test+' · '+orgLabel(r.organisation)),el('span',range(r),'range'));a.append(top,el('p',context(r),'context'));if(r.interval_type!=='reference_interval')a.append(el('p','เป็นเกณฑ์ที่แหล่งข้อมูลระบุ ยังไม่ใช้ตัดสินผลรายบุคคล','context'));
const detail=el('details');detail.append(el('summary','ดูที่มาและเงื่อนไข'));const body=el('div',undefined,'record-details'),dl=el('dl');for(const [k,v] of [['วิธีตรวจ',r.method||'ยังไม่ระบุในชุดข้อมูล'],['สิ่งส่งตรวจ',r.specimen||'ดูรายละเอียดในต้นฉบับ'],['วันที่เอกสาร',r.source_document_date||'ไม่พบวันที่ฉบับในเอกสารนี้'],['ตำแหน่ง', 'หน้า '+r.page],['ขอบเขต','ข้อมูลอ้างอิงจากคู่มือ ไม่ใช่การวินิจฉัย']])dl.append(el('dt',k),el('dd',v));body.append(dl);const links=el('div',undefined,'links');links.append(sourceLink('เปิดเอกสารต้นทาง',r.source_url),sourceLink('ดูสำเนาที่ใช้ตรวจข้อมูล','/source/'+encodeURIComponent(r.source_id)+'#page='+r.page));body.append(links);detail.append(body);a.append(detail);return a;}
function guidanceRecord(n){
 const a=el('article',undefined,'record guidance');a.append(el('h3',n.title_th),el('p',n.summary_th));
 const d=el('details');d.append(el('summary','ดูแนวทาง WHO และแหล่งอ้างอิง'));const b=el('div',undefined,'record-details');
 b.append(el('p',n.source_title+' · '+n.published),el('p','หน้า PDF '+n.pdf_page+' (เลขหน้าในเล่ม '+n.printed_page+') · '+n.section),el('p','สรุปภาษาไทยเพื่อการศึกษาโดย ResultScope ไม่ใช่คำแปลที่ WHO จัดทำหรือรับรอง · '+n.license));
 const links=el('div',undefined,'links');links.append(sourceLink('ต้นฉบับ WHO',n.source_url),sourceLink('สำเนาที่ใช้อ้างอิง','/source/'+encodeURIComponent(n.source_id)+'#page='+n.pdf_page),sourceLink('เงื่อนไขการใช้',n.license_url));b.append(links);d.append(b);a.append(d);return a;
}
let controller=null;
async function search(){if(controller)controller.abort();const active=new AbortController();controller=active;const query=$('query').value.trim();if(!query)return;$('search-button').disabled=true;$('status').className='';$('status').textContent='กำลังค้นข้อมูล…';$('results').hidden=true;$('empty').hidden=true;
try{const resp=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,organisation:$('organisation').value||null,sex:$('sex').value||null,method:'tree'}),signal:active.signal});if(!resp.ok)throw new Error('request_failed');const result=await resp.json();if(controller!==active)return;const notes=result.guidance||[];const count=result.records.length+notes.length;$('records').replaceChildren(...result.records.map(record),...notes.map(guidanceRecord));$('results').hidden=count===0;$('empty').hidden=count>0;$('status').textContent=count?'พบ '+count+' รายการจากแหล่งอ้างอิง'+(result.truncated?' · มีรายการเพิ่มเติม ลองเลือกแหล่งข้อมูล':''):'ไม่พบข้อมูลที่ตรงกับคำค้น';}catch(e){if(e.name!=='AbortError'){$('status').className='error';$('status').textContent='ค้นข้อมูลไม่สำเร็จ ตรวจว่าเซิร์ฟเวอร์ยังเปิดอยู่ แล้วลองอีกครั้ง';}}finally{if(controller===active)$('search-button').disabled=false;}}
$('search-form').addEventListener('submit',e=>{e.preventDefault();search();});document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{$('query').value=b.dataset.query;search();}));$('clear').addEventListener('click',()=>{if(controller)controller.abort();controller=null;$('query').value='';$('status').textContent='';$('results').hidden=true;$('empty').hidden=true;$('search-button').disabled=false;$('query').focus();});
function drawTree(n){const li=el('li',n.title||n.record_id);if(n.children?.length){const ul=el('ul');ul.append(...n.children.map(drawTree));li.append(ul);}return li;}
fetch('/api/meta').then(r=>{if(!r.ok)throw new Error();return r.json();}).then(m=>{$('meta').textContent='มีคู่มือ '+m.sources+' ฉบับ จาก '+m.organisations.length+' สถาบัน และข้อมูลอ้างอิง '+m.records+' รายการ พร้อมแนวทาง WHO '+m.guideline_sources+' ฉบับ';for(const o of m.organisations){const opt=el('option',orgLabel(o));opt.value=o;$('organisation').append(opt);}const ul=el('ul');ul.append(drawTree(m.tree));if(m.guideline_tree)ul.append(drawTree(m.guideline_tree));$('tree').append(ul);}).catch(()=>{$('meta').textContent='โหลดรายละเอียดชุดข้อมูลไม่สำเร็จ ลองเปิดหน้าใหม่เมื่อเซิร์ฟเวอร์พร้อม';});
