/* Offline browser verification. Explicit API doubles are labeled in the manifest. */
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'docs/assets/screenshots-v2');
const python=process.env.RESULTSCOPE_PYTHON||path.join(root,'.venv',process.platform==='win32'?'Scripts/python.exe':'bin/python');
const port=process.env.RESULTSCOPE_TEST_PORT||'8765',base=`http://127.0.0.1:${port}`;
const env={...process.env,PROVIDER_NETWORK_ENABLED:'false',VISION_ENABLED:'false',GUARD_API_KEY:'',LLM_API_KEY:'',DEMO_ACCESS_CODE:'',SESSION_SIGNING_KEY:'offline-browser-test-secret-32-characters',ADMIN_SETTINGS_PATH:path.join(os.tmpdir(),`resultscope-no-settings-${process.pid}.json`)};delete env.VERCEL;
const entries=[],checks=[],errors=[];
const rows=[{id:'r1',name:'ALT',value:'42',unit:'U/L',reference:'0-40',printed_flag:'H',status:'high'}];
const report={fields:rows,warnings:['Scripted UI test row; this is not measured OCR output.'],confirmed:false,data_class:'synthetic',demo_id:'01_A_Liver'};
const answer={reply:'This is a **scripted interface test**, not a live model response. Reference intervals can differ between laboratories. [nlm-reading-results]',sources:[{id:'nlm-reading-results',title:'How to understand your lab results',url:'https://medlineplus.gov/lab-tests/how-to-understand-your-lab-results/',publisher:'MedlinePlus',data_class:'public_education'}],observations:[],followups:['อธิบายให้ง่ายขึ้นได้ไหม'],action:'answer',retrieval:'lexical',state_token:'scripted-ui-token',request_id:'offline-ui-test'};
function record(name){checks.push(name)}
async function snap(page,name,mode){await page.screenshot({path:path.join(out,name),fullPage:true});entries.push({file:name,mode,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(out,name))).digest('hex')})}
async function ready(page){await page.goto(base);await page.locator('#connection-label').filter({hasText:'Connect AI'}).waitFor();await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(1200)}
async function withinViewport(page){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'No horizontal page overflow')}
(async()=>{fs.mkdirSync(out,{recursive:true});const server=spawn(python,['-m','uvicorn','main:app','--host','127.0.0.1','--port',port],{cwd:root,env,stdio:['ignore','ignore','pipe']});let browser;let serverError='';server.stderr.on('data',x=>{if(String(x).includes('Error'))serverError+=String(x)});
try{
 for(let i=0;i<100;i++){try{if((await fetch(base+'/health')).ok)break}catch{} await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch({headless:true});
 const desktop=await browser.newPage({viewport:{width:1440,height:1000}});desktop.on('pageerror',e=>errors.push(e.message));await ready(desktop);await withinViewport(desktop);await snap(desktop,'01-conversation-desktop.png','real local UI; providers disabled');record('Desktop composer and original purple theme');
 await desktop.locator('#message-input').fill('What is a reference range?');await desktop.locator('#send-button').click();await desktop.locator('.error-answer').waitFor();assert.match(await desktop.locator('.error-answer').innerText(),/not configured|not connected/);record('Offline mode shows a real provider setup error, never a canned AI answer');await snap(desktop,'02-offline-recovery.png','real local API error; no model calls');
 await desktop.locator('#new-chat').click();await desktop.locator('#confirm-reset').click();await desktop.locator('#welcome').waitFor({state:'visible'});record('Reset clears conversation');
 await desktop.locator('[data-open="sources-dialog"]').first().click();assert.ok(await desktop.locator('.reference-item').count()>5);await desktop.locator('[aria-label="Close references"]').click();record('Reference library displays real publishers');
 await desktop.locator('[data-open="demo-dialog"]').first().click();await desktop.locator('.demo-card').last().waitFor();assert.equal(await desktop.locator('.demo-card').count(),6);await snap(desktop,'03-six-supplied-reports.png','real supplied synthetic artifacts; no OCR');await desktop.getByRole('button',{name:'Open Liver panel',exact:true}).click();await desktop.locator('#report-image').waitFor({state:'visible'});assert.equal(await desktop.locator('#report-image').evaluate(el=>el.naturalWidth>0),true);record('Supplied artifact preview loads');
 await desktop.route('**/api/v2/demos/01_A_Liver/read',route=>route.fulfill({json:{report,draft_token:'scripted-ui-draft'}}));
 await desktop.route('**/api/v2/reports/confirm',async route=>{const payload=route.request().postDataJSON();assert.equal(payload.fields[0].value,'32');await route.fulfill({json:{report:{...report,fields:[{...rows[0],value:'32',status:'within'}],confirmed:true},state_token:'scripted-ui-token'}})});
 await desktop.locator('#read-report').click();await desktop.locator('#confirm-report').waitFor({state:'visible'});await desktop.locator('[data-key="value"]').fill('32');await snap(desktop,'04-report-review-scripted.png','explicit vision API double; row is not measured OCR');await desktop.locator('#confirm-report').click();await desktop.locator('#context-chip').waitFor({state:'visible'});record('Report correction and explicit confirmation UI');
 let received=[];await desktop.route('**/api/v2/chat/stream',route=>{received.push(route.request().postDataJSON());return route.fulfill({contentType:'text/event-stream',body:'event: status\ndata: {"message":"Scripted offline test"}\n\nevent: answer\ndata: '+JSON.stringify(answer)+'\n\n'})});
 await desktop.locator('#message-input').fill('Explain this, please.');await desktop.locator('#send-button').click();await desktop.locator('.answer-source-list a').first().waitFor();assert.equal(await desktop.locator('.answer-source-list a').first().getAttribute('href'),answer.sources[0].url);await desktop.locator('.answer-followups button').last().click();await desktop.waitForFunction(()=>document.querySelectorAll('.answer-prose').length===2);assert.equal(received[1].message,'อธิบายให้ง่ายขึ้นได้ไหม');assert.equal(received[1].state_token,'scripted-ui-token');record('Scripted multi-turn answer, citations and Thai follow-up preserve context');await snap(desktop,'05-conversation-scripted.png','explicit answer API double; not live LLM evidence');
 const downloadPromise=desktop.waitForEvent('download');await desktop.locator('#export-chat').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'ResultScope-conversation.md');assert.ok(fs.readFileSync(await download.path(),'utf8').includes(answer.sources[0].url));record('Conversation export');
 await desktop.locator('[data-open="tour-dialog"]').first().click();await desktop.waitForFunction(()=>document.querySelector('hyperframes-player').ready===true,{timeout:10000});await desktop.evaluate(()=>document.querySelector('hyperframes-player').seek(11.8));await desktop.waitForTimeout(300);await snap(desktop,'06-hyperframes-introduction.png','real Hyperframes player, held composition frame');await desktop.locator('[aria-label="Close introduction"]').click();record('Hyperframes player loads and seeks');
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));await ready(mobile);await withinViewport(mobile);assert.equal(await mobile.locator('#sidebar').isVisible(),false);await snap(mobile,'07-conversation-mobile.png','real local mobile UI; providers disabled');await mobile.locator('#mobile-menu').click();await mobile.locator('#sidebar').waitFor({state:'visible'});await mobile.locator('[data-open="demo-dialog"]').first().click();await mobile.locator('.demo-card').last().waitFor();await withinViewport(mobile);await snap(mobile,'08-sample-gallery-mobile.png','real supplied synthetic report gallery');await mobile.getByRole('button',{name:'Open Thyroid panel',exact:true}).click();await mobile.locator('#report-image').waitFor({state:'visible'});await snap(mobile,'09-report-mobile.png','real supplied synthetic thyroid PNG; no OCR');record('390 px mobile navigation, gallery and document dialog');
 const reduced=await browser.newPage({viewport:{width:1024,height:900},reducedMotion:'reduce'});reduced.on('pageerror',e=>errors.push(e.message));await ready(reduced);await reduced.keyboard.press('Tab');assert.equal(await reduced.locator(':focus').innerText(),'Skip to conversation');await reduced.keyboard.press('Enter');assert.equal(await reduced.locator('#message-input').evaluate(el=>el===document.activeElement),true);await reduced.locator('[data-open="settings-dialog"]').first().click();await reduced.keyboard.press('Escape');assert.equal(await reduced.locator('#settings-dialog').evaluate(el=>el.open),false);record('Reduced motion, keyboard skip link and Escape dialog closure');
 await desktop.goto(base+'/static/docs/user-guide.html');await desktop.evaluate(()=>document.fonts.ready);await snap(desktop,'10-user-guide.png','current HTML guide');
 assert.deepEqual(errors,[],'No uncaught browser errors');record('No uncaught browser errors');
 fs.writeFileSync(path.join(out,'CAPTURE_MANIFEST.json'),JSON.stringify({version:'2.0.0',date:'2026-10-05',provider_calls:0,checks,entries,limits:['API doubles do not establish OCR or LLM quality.','Actual Vercel deployment and live providers were not tested.']},null,2)+'\n');console.log(JSON.stringify({status:'passed',checks:checks.length,screenshots:entries.length,provider_calls:0}));
}finally{await browser?.close();server.kill();if(serverError)console.error(serverError.slice(0,600))}})().catch(error=>{console.error(error);process.exitCode=1});
